version: '3'
services:
  app:
    container_name: siege-stress-test-app
    build: .
    ports:
      - '${APP_PORT}:3000'
    env_file:
      - .env
    depends_on:
      - postgresql

  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'

volumes:
  postgresql_data: {}

